services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    # - name=value
    # MONGO_INITDB_ROOT_USERNAME: tugudush
    # MONGO_INITDB_ROOT_PASSWORD: accessdenied123
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net
  # backend:

  # frontend:
volumes:
  data:
