services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    volumes:
      - data:/data/db
    # environment:
    # - name=value
    # MONGO_INITDB_ROOT_USERNAME: username
    # MONGO_INITDB_ROOT_PASSWORD: password
    env_file:
      - ./env/mongo.env      
    # networks:
    #   - goals-net
  backend:
    build: ./backend    
    container_name: backend
    # build:
    #   context: ./backend
    #   dockerfile: dockerfile
    #   args:
    #     DEFAULT_PORT: 80
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      # - ./env/backend.env      
      - ./env/mongo.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
