services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    # - name=value
    # MONGO_INITDB_ROOT_USERNAME: tugudush
    # MONGO_INITDB_ROOT_PASSWORD: accessdenied123
    env_file:
      - ./env/mongo.env      
    # networks:
    #   - goals-net
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: dockerfile
    #   args:
    #     DEFAULT_PORT: 80
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env      
    depends_on:
      - mongodb
  # frontend:
volumes:
  data:
  logs:
